apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: x7z8n9kea-go-gitops
  description: This is GitOps manifest for x7z8n9kea-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: x7z8n9kea-go
    backstage.io/kubernetes-id: x7z8n9kea-go 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: x7z8n9kea-go-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:x7z8n9kea-go
